# Generated by Django 5.2.5 on 2025-09-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('subheading', models.CharField(blank=True, max_length=200)),
                ('paragraph', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner/')),
                ('button_text', models.CharField(blank=True, max_length=100)),
                ('button_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('fa-gem', 'Gem'), ('fa-paper-plane', 'Paper Plane'), ('fa-rocket', 'Rocket'), ('fa-signal', 'Signal')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright', models.CharField(max_length=200)),
                ('demo_images_link', models.URLField(blank=True)),
                ('design_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MiniPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='miniposts/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('button_text', models.CharField(blank=True, max_length=100)),
                ('button_link', models.URLField(blank=True)),
            ],
        ),
    ]
