# Generated by Django 5.2.5 on 2025-10-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_banner_contactinfo_feature_footer_minipost_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='paragraph',
        ),
        migrations.AddField(
            model_name='banner',
            name='description1',
            field=models.TextField(default="XFED Tax Solutions is committed to providing efficient and effective tax and tax related services to America's taxpayer population."),
        ),
        migrations.AddField(
            model_name='banner',
            name='description2',
            field=models.TextField(default="Whether you are an individual or business or both, America's largest network of former IRS tax professionals can provide the services you need."),
        ),
        migrations.AddField(
            model_name='banner',
            name='description3',
            field=models.TextField(default="For specific information about how we can help you, please fill out our <a href='#'>brief questionnaire</a> or call us at [Justin's Personal Cell Phone Number]."),
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_link',
            field=models.URLField(blank=True, default='#'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_text',
            field=models.CharField(default='Learn More', max_length=100),
        ),
        migrations.AlterField(
            model_name='banner',
            name='heading',
            field=models.CharField(default='XFED Tax Solutions', max_length=200),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subheading',
            field=models.CharField(default='Former Feds Making The System Work For You!', max_length=200),
        ),
    ]
