# Generated by Django 5.2.5 on 2025-10-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_banner_paragraph_banner_description1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=models.TextField(default='Enter text here'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.CharField(choices=[('fa-gem', 'Gem'), ('fa-paper-plane', 'Paper Plane'), ('fa-rocket', 'Rocket'), ('fa-signal', 'Signal')], default='fa-gem', max_length=50),
        ),
        migrations.AlterField(
            model_name='feature',
            name='title',
            field=models.CharField(default='Enter text here', max_length=100),
        ),
    ]
