# Generated by Django 5.2.5 on 2025-10-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_manual_migration_default_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='button_link',
            field=models.CharField(blank=True, default='/', max_length=200),
        ),
    ]
