# Generated by Django 5.2.5 on 2025-10-20 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_banner_button_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('homepage', 'Homepage'), ('generic', 'Generic Page'), ('elements', 'Elements Page')], help_text='Which page this content appears on', max_length=50, verbose_name='Page')),
                ('section_type', models.CharField(choices=[('header', 'Page Header'), ('main_content', 'Main Content Section'), ('sidebar', 'Sidebar Content'), ('footer', 'Footer Content')], help_text='What type of section this content represents', max_length=50, verbose_name='Section Type')),
                ('title', models.CharField(help_text='The main heading for this section', max_length=200, verbose_name='Section Title')),
                ('content', models.TextField(help_text='The main text content for this section (HTML allowed)', verbose_name='Section Content')),
                ('image', models.ImageField(blank=True, help_text='Optional image for this section', null=True, upload_to='page_content/', verbose_name='Section Image')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which this section appears (0 = first, 1 = second, etc.)', verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this section from the website', verbose_name='Show on Website')),
            ],
            options={
                'verbose_name': 'Page Section',
                'verbose_name_plural': 'Page Sections',
                'ordering': ['page', 'section_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitter', 'Twitter'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('snapchat', 'Snapchat'), ('medium', 'Medium')], max_length=50, verbose_name='Social Media Platform')),
                ('url', models.URLField(help_text='Full URL to your social media profile', verbose_name='Profile URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on Website')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_link',
            field=models.CharField(blank=True, default='/', help_text="Where the button should link to (e.g., '/contact/' or 'https://example.com')", max_length=200, verbose_name='Button Link URL'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_text',
            field=models.CharField(default='Learn More', help_text='The text that appears on the button in the banner', max_length=100, verbose_name='Button Text'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='description1',
            field=models.TextField(default="XFED Tax Solutions is committed to providing efficient and effective tax and tax related services to America's taxpayer population.", help_text='The first paragraph of text in the banner section', verbose_name='First Description Paragraph'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='description2',
            field=models.TextField(default="Whether you are an individual or business or both, America's largest network of former IRS tax professionals can provide the services you need.", help_text='The second paragraph of text in the banner section', verbose_name='Second Description Paragraph'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='description3',
            field=models.TextField(default="For specific information about how we can help you, please fill out our <a href='#'>brief questionnaire</a> or call us at [Justin's Personal Cell Phone Number].", help_text="The third paragraph of text in the banner section. You can include HTML links like <a href='#'>link text</a>", verbose_name='Third Description Paragraph'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='heading',
            field=models.CharField(default='XFED Tax Solutions', help_text='The large heading text that appears at the top of the homepage banner', max_length=200, verbose_name='Main Headline'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, help_text='The image that appears on the right side of the banner (optional)', null=True, upload_to='banner/', verbose_name='Banner Image'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subheading',
            field=models.CharField(default='Former Feds Making The System Work For You!', help_text='The smaller text that appears directly under the main headline', max_length=200, verbose_name='Tagline'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=models.TextField(default='Enter text here', help_text='Brief description explaining this feature or service', verbose_name='Feature Description'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.CharField(choices=[('fa-gem', 'Gem'), ('fa-paper-plane', 'Paper Plane'), ('fa-rocket', 'Rocket'), ('fa-signal', 'Signal')], default='fa-gem', help_text='Choose an icon that represents this feature', max_length=50, verbose_name='Feature Icon'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='title',
            field=models.CharField(default='Enter text here', help_text="Short title for this feature (appears in the 'More About Us' section)", max_length=100, verbose_name='Feature Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='button_link',
            field=models.URLField(blank=True, help_text='URL where this article can be read in full', verbose_name='Article Link'),
        ),
        migrations.AlterField(
            model_name='post',
            name='button_text',
            field=models.CharField(blank=True, help_text="Text for the button (e.g., 'Read More', 'Learn More')", max_length=100, verbose_name='Read More Button Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(help_text='Brief description or excerpt of the article', verbose_name='Article Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text="Image that appears with this article (appears in the 'Ipsum sed dolor' section)", null=True, upload_to='posts/', verbose_name='Article Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Title of the article or blog post', max_length=100, verbose_name='Article Title'),
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Text that appears in the navigation menu', max_length=100, verbose_name='Menu Item Text')),
                ('url', models.CharField(help_text="Where this menu item links to (e.g., '/contact/' or 'https://example.com')", max_length=200, verbose_name='Link URL')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which this item appears in the menu', verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this menu item', verbose_name='Show in Menu')),
                ('parent', models.ForeignKey(blank=True, help_text='Leave blank for top-level menu items', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.navigationitem', verbose_name='Parent Menu Item')),
            ],
            options={
                'verbose_name': 'Navigation Menu Item',
                'verbose_name_plural': 'Navigation Menu Items',
                'ordering': ['order'],
            },
        ),
    ]
