# Generated by Django 5.2.5 on 2025-10-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_pagecontent_socialmedialink_alter_banner_button_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Contact Information', 'verbose_name_plural': 'Contact Information'},
        ),
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'Footer Information', 'verbose_name_plural': 'Footer Information'},
        ),
        migrations.AlterModelOptions(
            name='genericpagesection',
            options={'verbose_name': 'Generic Page Section', 'verbose_name_plural': 'Generic Page Sections'},
        ),
        migrations.AlterModelOptions(
            name='minipost',
            options={'verbose_name': 'Sidebar Mini Post', 'verbose_name_plural': 'Sidebar Mini Posts'},
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.TextField(help_text='Full business address displayed in the contact section', verbose_name='Business Address'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(help_text="Email address displayed in the 'Get in touch' section", max_length=254, verbose_name='Contact Email Address'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(help_text="Phone number displayed in the contact section (e.g., '(555) 123-4567')", max_length=50, verbose_name='Contact Phone Number'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='copyright',
            field=models.CharField(help_text='Copyright notice that appears at the bottom of every page', max_length=200, verbose_name='Copyright Text'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='demo_images_link',
            field=models.URLField(blank=True, help_text='Optional link to credit demo images (leave blank if not needed)', verbose_name='Demo Images Credit Link'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='design_link',
            field=models.URLField(blank=True, help_text='Optional link to credit website design (leave blank if not needed)', verbose_name='Design Credit Link'),
        ),
        migrations.AlterField(
            model_name='genericpagesection',
            name='content',
            field=models.TextField(help_text='The main text content for this section (HTML formatting allowed)', verbose_name='Section Content'),
        ),
        migrations.AlterField(
            model_name='genericpagesection',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for this section', null=True, upload_to='generic/', verbose_name='Section Image'),
        ),
        migrations.AlterField(
            model_name='genericpagesection',
            name='title',
            field=models.CharField(help_text='The main heading for this page section', max_length=200, verbose_name='Section Title'),
        ),
        migrations.AlterField(
            model_name='minipost',
            name='description',
            field=models.TextField(help_text='Brief text content for this sidebar post', verbose_name='Sidebar Post Text'),
        ),
        migrations.AlterField(
            model_name='minipost',
            name='image',
            field=models.ImageField(blank=True, help_text='Small image that appears in the sidebar mini-posts section', null=True, upload_to='miniposts/', verbose_name='Sidebar Post Image'),
        ),
    ]
