# Generated by Django 5.2.5 on 2025-10-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_contactinfo_options_alter_footer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title that appears in the browser tab and page header', max_length=200, verbose_name='Page Title')),
                ('slug', models.SlugField(help_text="The URL path for this page (e.g., 'about-us' creates /about-us/). Only letters, numbers, and hyphens allowed.", max_length=200, unique=True, verbose_name='Page URL')),
                ('template_type', models.CharField(choices=[('generic', 'Generic Template (Simple content layout)'), ('elements', 'Elements Template (Feature-rich with forms, tables, etc.)'), ('index', 'Homepage Template (Banner + features + posts layout)')], default='generic', help_text='Choose the layout style for this page', max_length=50, verbose_name='Page Template')),
                ('meta_description', models.TextField(blank=True, help_text='Brief description for search engines (160 characters max)', max_length=160, verbose_name='SEO Description')),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide this page from the website', verbose_name='Publish Page')),
                ('show_in_navigation', models.BooleanField(default=False, help_text='Check to automatically add this page to the main navigation menu', verbose_name='Show in Main Navigation')),
                ('navigation_order', models.PositiveIntegerField(default=0, help_text='Order in navigation menu (lower numbers appear first)', verbose_name='Navigation Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom Page',
                'verbose_name_plural': 'Custom Pages',
                'ordering': ['navigation_order', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='page',
            field=models.CharField(help_text="Which page this content appears on (use page slug for dynamic pages, or 'homepage'/'generic'/'elements' for default pages)", max_length=100, verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='section_type',
            field=models.CharField(choices=[('header', 'Page Header'), ('main_content', 'Main Content Section'), ('sidebar', 'Sidebar Content'), ('footer', 'Footer Content'), ('banner', 'Banner Section'), ('features', 'Features Section'), ('posts', 'Posts Section')], help_text='What type of section this content represents', max_length=50, verbose_name='Section Type'),
        ),
    ]
