# Generated by Django 5.2.5 on 2025-11-08 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_dynamicpage_alter_pagecontent_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title that appears at the top of the form', max_length=200, verbose_name='Form Title')),
                ('slug', models.SlugField(help_text="The URL path for this form (e.g., 'client-intake' creates /intake/client-intake/)", max_length=200, unique=True, verbose_name='Form URL')),
                ('description', models.TextField(blank=True, help_text='Optional description that appears below the title', verbose_name='Form Description')),
                ('success_message', models.TextField(default='Thank you for your submission! We will contact you soon.', help_text='Message shown after successful form submission', verbose_name='Success Message')),
                ('email_recipients', models.TextField(help_text='Email addresses to send form submissions to (one per line)', verbose_name='Email Recipients')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to disable this form', verbose_name='Form Active')),
                ('allow_file_uploads', models.BooleanField(default=True, help_text='Allow users to upload documents with their submission', verbose_name='Allow File Uploads')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Intake Form',
                'verbose_name_plural': 'Intake Forms',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='dynamicpage',
            name='template_type',
            field=models.CharField(choices=[('generic', 'Generic Template (Simple content layout)'), ('elements', 'Elements Template (Feature-rich with forms, tables, etc.)'), ('index', 'Homepage Template (Banner + features + posts layout)'), ('intake', 'Intake Form Template (Custom intake forms)')], default='generic', help_text='Choose the layout style for this page', max_length=50, verbose_name='Page Template'),
        ),
        migrations.CreateModel(
            name='IntakeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('data', models.JSONField(help_text='Form field data submitted by the user', verbose_name='Submission Data')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='main.intakeform', verbose_name='Intake Form')),
            ],
            options={
                'verbose_name': 'Form Submission',
                'verbose_name_plural': 'Form Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='IntakeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='intake_uploads/%Y/%m/', verbose_name='Uploaded File')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Original Filename')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='main.intakesubmission', verbose_name='Form Submission')),
            ],
            options={
                'verbose_name': 'Uploaded File',
                'verbose_name_plural': 'Uploaded Files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='IntakeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='The label that appears above the field', max_length=100, verbose_name='Field Label')),
                ('field_name', models.CharField(help_text='Internal name for the field (letters, numbers, underscores only)', max_length=50, verbose_name='Field Name')),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('email', 'Email Input'), ('phone', 'Phone Number'), ('textarea', 'Text Area (Multi-line)'), ('select', 'Dropdown Select'), ('checkbox', 'Checkbox'), ('radio', 'Radio Button Group'), ('file', 'File Upload')], help_text='What type of input field this is', max_length=20, verbose_name='Field Type')),
                ('placeholder', models.CharField(blank=True, help_text='Optional placeholder text inside the field', max_length=200, verbose_name='Placeholder Text')),
                ('choices', models.TextField(blank=True, help_text='For dropdown or radio fields, enter choices (one per line)', verbose_name='Choices (for select/radio)')),
                ('is_required', models.BooleanField(default=False, help_text='Check if this field must be filled out', verbose_name='Required Field')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which this field appears (0 = first, 1 = second, etc.)', verbose_name='Display Order')),
                ('help_text', models.CharField(blank=True, help_text='Optional help text that appears below the field', max_length=200, verbose_name='Help Text')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='main.intakeform', verbose_name='Intake Form')),
            ],
            options={
                'verbose_name': 'Form Field',
                'verbose_name_plural': 'Form Fields',
                'ordering': ['form', 'order'],
                'unique_together': {('form', 'field_name')},
            },
        ),
    ]
