# Generated by Django 5.2.5 on 2025-11-08 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_intakeform_alter_dynamicpage_template_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intakesubmission',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes about this submission (not visible to client)', verbose_name='Internal Notes'),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Staff member responsible for this submission', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='first_contacted_at',
            field=models.DateTimeField(blank=True, help_text='When we first contacted the client', null=True, verbose_name='First Contact Date'),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='last_contact_at',
            field=models.DateTimeField(blank=True, help_text='Most recent contact with client', null=True, verbose_name='Last Contact Date'),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='next_followup_date',
            field=models.DateField(blank=True, help_text='When to follow up with this client', null=True, verbose_name='Next Follow-up Date'),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='priority',
            field=models.CharField(choices=[('low', 'Low Priority'), ('normal', 'Normal Priority'), ('high', 'High Priority'), ('urgent', 'Urgent')], default='normal', help_text='Priority level for follow-up', max_length=10, verbose_name='Priority Level'),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='status',
            field=models.CharField(choices=[('new', 'New - Needs Review'), ('reviewed', 'Reviewed - Needs Response'), ('contacted', 'Client Contacted'), ('scheduled', 'Meeting Scheduled'), ('completed', 'Process Completed'), ('declined', 'Declined/Not Proceeding')], default='new', help_text='Current status of this submission', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
