# Generated by Django 5.2.5 on 2025-11-08 21:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_intakesubmission_admin_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigationitem',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Navigation Item', 'verbose_name_plural': 'Navigation Items'},
        ),
        migrations.AlterModelOptions(
            name='socialmedialink',
            options={'ordering': ['order', 'platform'], 'verbose_name': 'Social Media Link', 'verbose_name_plural': 'Social Media Links'},
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 8, 21, 56, 57, 54929, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='icon_class',
            field=models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fa-home', 'fa-envelope')", max_length=50, verbose_name='Icon Class (Optional)'),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='opens_new_window',
            field=models.BooleanField(default=False, help_text='Check if this link should open in a new tab/window', verbose_name='Open in New Window'),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to temporarily hide this menu item', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first. Use 10, 20, 30... to leave room for reordering.', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Leave blank for top-level menu items. Select a parent to create dropdown submenu items.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.navigationitem', verbose_name='Parent Menu Item'),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='title',
            field=models.CharField(help_text='The text that will appear in the navigation menu', max_length=100, verbose_name='Menu Title'),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='url',
            field=models.CharField(help_text="Where this menu item links to (e.g., '/contact/', 'https://example.com', or '#' for dropdowns)", max_length=200, verbose_name='Link URL'),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to temporarily hide this social link', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='platform',
            field=models.CharField(choices=[('twitter', 'Twitter'), ('facebook-f', 'Facebook'), ('instagram', 'Instagram'), ('linkedin-in', 'LinkedIn'), ('youtube', 'YouTube'), ('snapchat-ghost', 'Snapchat'), ('medium-m', 'Medium'), ('github', 'GitHub'), ('envelope', 'Email')], help_text='Choose the social media platform', max_length=20, verbose_name='Social Platform'),
        ),
    ]
