# Generated by Django 5.2.5 on 2025-12-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_navigationitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.CharField(choices=[('fa-gem', '💎 Gem'), ('fa-paper-plane', '✈️ Paper Plane'), ('fa-rocket', '🚀 Rocket'), ('fa-signal', '📶 Signal'), ('fa-shield-alt', '🛡️ Shield'), ('fa-file-invoice-dollar', '💵 Invoice/Dollar'), ('fa-handshake', '🤝 Handshake'), ('fa-building', '🏢 Building'), ('fa-balance-scale', '⚖️ Balance Scale'), ('fa-calculator', '🔢 Calculator'), ('fa-file-alt', '📄 Document'), ('fa-user-tie', '👔 Professional'), ('fa-gavel', '🔨 Gavel'), ('fa-landmark', '🏛️ Landmark/Government'), ('fa-dollar-sign', '💲 Dollar Sign'), ('fa-chart-line', '📈 Chart'), ('fa-briefcase', '💼 Briefcase'), ('fa-search', '🔍 Search'), ('fa-check-circle', '✅ Checkmark')], default='fa-shield-alt', help_text='Choose an icon that represents this feature', max_length=50, verbose_name='Feature Icon'),
        ),
    ]
