# Generated by Django 5.2.5 on 2026-02-13 20:44

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_expand_feature_icons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intakefile',
            name='file',
            field=models.FileField(upload_to=main.models.intake_file_upload_path, verbose_name='Uploaded File'),
        ),
    ]
